### ISSUE TITLE
Allow filtering tasks by the worker href

### ISSUE THREAD

**Issue by dralley** [pulp/pulp-cli#450] opened 2022-01-19 20:48 UTC
e.g. `pulp task list --worker /pulp/api/v3/workers/6292f6e9-1f50-4597-bf6f-e64a2ef1ae4e/`

It's something you can do via the API, but the CLI doesn't support the option.  Support would like to be able to view the subset of tasks that have run on a particular worker easily.

**Comment by mdellweg** [comment] 2022-09-27 08:46
I think this is notw a duplicate of #543

**Closed by mdellweg** 2022-09-27 08:46 UTC
Labels: Duplicate, feature request, easy fix
