### ISSUE TITLE
Run the importer via CLI 

### ISSUE THREAD

**Issue by rochacbruno** [pulp/pulp-cli#304] opened 2021-07-14 16:50 UTC
As described here: https://gist.github.com/rochacbruno/5c9e0fd34269ab24d0ca6c3e8f003136

After the `importer` is created it must have a task trigerred and it is done via `POST` request providing `toc` or `path` argument.

```bash
http -a admin:admin \
   POST http://0.0.0.0:5001/pulp/api/v3/importers/core/pulp/3f8d3dd5-8908-4ba1-bd65-2daadf6c76ff/imports/ \
   toc="/tmp/export-e3a52698-2913-45b6-bf75-51640126c6bc-20210714_1503-toc.json"
```

The above is not yet supported by the pulp-cli

**expected**

```bash
pulp importer pulp run --name=my_importer --toc=/path/to.json --path=/path/to.tar.gz
```

**Comment by rochacbruno** [comment] 2021-07-14 16:54
This @ggainey  PR mentions a `run` subcommand https://github.com/pulp/pulp-cli/pull/195/files

But when I try using 0.11.0-dev

```bash
❯ pulp importer pulp run
Usage: pulp importer pulp [OPTIONS] COMMAND [ARGS]...
Try 'pulp importer pulp --help' for help.

Error: No such command 'run'.

❯ pulp importer pulp --help
Usage: pulp importer pulp [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  create
  destroy
  list
  show
  update

❯ pulp importer --help     
Usage: pulp importer [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  pulp

```

**Comment by ggainey** [comment] 2021-07-14 16:57
> This @ggainey PR mentions a `run` subcommand https://github.com/pulp/pulp-cli/pull/195/files

That PR wasn't merged, it was **closed** - cli refactoring was happening, and it wasn't worth trying to keep up at that point. There is no 'run' command currently available.

**Comment by mdellweg** [comment] 2021-07-21 14:46
#93 is the dupe of this.

**Closed by mdellweg** 2021-07-21 14:46 UTC
