### ISSUE TITLE
Add "--metadata-signing-service" option to rpm

### ISSUE THREAD

**Issue by tjmullicani** [pulp/pulp-cli#607] opened 2022-11-22 18:09 UTC
## Summary
Add `--metadata-signing-service` option to `pulp rpm` command.

**Comment by mdellweg** [comment] 2022-11-23 09:16
This is a dupe of #605 .

**Comment by mdellweg** [comment] 2022-11-23 14:42
Please refer to the existing issue in any pull requests.

**Closed by mdellweg** 2022-11-23 14:42 UTC
Labels: Duplicate, feature request
